<MyPopup>:
    title: 'Please add name'
    size_hint: 0.4, 0.2
    pos_hint:{"x":0.3 , "y":0.4}
    auto_dismiss: False
    input: input.text

    BoxLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size

        TextInput:
            id: input
            multiline: False
            hint_text:'name'

        Button:
            text: 'Add'
            background_color: 0,1,255,0.7
            on_press:
                root.cancel()